package org.angular.model.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.angular.model.enums.WeekDay;

/**
 * Clase Schedule, que representa un turno (dia, hora de inicio y hora de fin)
 * @author fabad
 *
 */
@Entity
@Table(name="SCHEDULE")
public class Schedule implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -345412756906437389L;

	/** The id. */
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID_SCHEDULE")
	private Integer id;
	
	/** The week day. */
	@Column(name="WEEK_DAY")
	private Integer weekDay;
	
	/** The start hour. */
	@Temporal(TemporalType.TIME)
	@Column(name="START_HOUR")
	private Date startHour;
	
	/** The end hour. */
	@Temporal(TemporalType.TIME)
	@Column(name="END_HOUR")
	private Date endHour;

	/**
	 * Gets the week day.
	 *
	 * @return the week day
	 */
	public WeekDay getWeekDay() {
		return WeekDay.getWeekDay(weekDay);
	}

	/**
	 * Sets the week day.
	 *
	 * @param weekDay the new week day
	 */
	public void setWeekDay(WeekDay weekDay) {
		this.weekDay = weekDay.getId();
	}
	
	/**
	 * Sets the week day.
	 *
	 * @param weekDay the new week day
	 */
	public void setWeekDay(Integer weekDay) {
		this.weekDay = weekDay;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the start hour.
	 *
	 * @return the start hour
	 */
	public Date getStartHour() {
		return startHour;
	}

	/**
	 * Sets the start hour.
	 *
	 * @param startHour the new start hour
	 */
	public void setStartHour(Date startHour) {
		this.startHour = startHour;
	}

	/**
	 * Gets the end hour.
	 *
	 * @return the end hour
	 */
	public Date getEndHour() {
		return endHour;
	}

	/**
	 * Sets the end hour.
	 *
	 * @param endHour the new end hour
	 */
	public void setEndHour(Date endHour) {
		this.endHour = endHour;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Schedule other = (Schedule) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * @overwrite toString()
	 * @return String returns this object in a String
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Schedule::[");
		sb.append(" " + super.toString() + "");
		sb.append(" id:=");
		sb.append(id);
		sb.append(" weekDay:=");
		sb.append(weekDay);
		sb.append(" startHour:=");
		sb.append(startHour);
		sb.append(" endHour:=");
		sb.append(endHour);
		sb.append(']');
		return sb.toString();
	}

	
	
}
