package org.angular.model.complexId;

import java.io.Serializable;
import java.util.Date;

import org.angular.model.entities.Court;
import org.angular.model.entities.Person;

/**
 * The Class CourtHireId.
 */
public class CourtHireId implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8233800212001147565L;
	
	/** The person. */
	private Person person;
	
	/** The court. */
	private Court court;
	
	/** The date. */
	private Date date;
	
	/**
	 * Gets the person.
	 *
	 * @return the person
	 */
	public Person getPerson() {
		return person;
	}
	
	/**
	 * Sets the person.
	 *
	 * @param person the new person
	 */
	public void setPerson(Person person) {
		this.person = person;
	}
	
	/**
	 * Gets the court.
	 *
	 * @return the court
	 */
	public Court getCourt() {
		return court;
	}
	
	/**
	 * Sets the court.
	 *
	 * @param court the new court
	 */
	public void setCourt(Court court) {
		this.court = court;
	}
	
	/**
	 * Gets the date.
	 *
	 * @return the date
	 */
	public Date getDate() {
		return date;
	}
	
	/**
	 * Sets the date.
	 *
	 * @param date the new date
	 */
	public void setDate(Date date) {
		this.date = date;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((court == null) ? 0 : court.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + ((person == null) ? 0 : person.hashCode());
		return result;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CourtHireId other = (CourtHireId) obj;
		if (court == null) {
			if (other.court != null)
				return false;
		} else if (!court.equals(other.court))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (person == null) {
			if (other.person != null)
				return false;
		} else if (!person.equals(other.person))
			return false;
		return true;
	}
	/**
	 * @autogenerated by CodeHaggis (http://sourceforge.net/projects/haggis)
	 * @overwrite toString()
	 * @return String returns this object in a String
	 */
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("CourtHireId::[");
		sb.append(" " + super.toString() + "");
		sb.append(" person:=");
		sb.append(person);
		sb.append(" court:=");
		sb.append(court);
		sb.append(" date:=");
		sb.append(date);
		sb.append(']');
		return sb.toString();
	}
	
	
	
	
	
	
	
}
