-- Insertar persona
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Fran', 'Abad', 'fabad', 26);
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Antonio', 'Abad', 'aabad', 60);
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Paloma', 'Navarro', 'pnavarro', 52);
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Silvia', 'Kournikova', 'skournikova', 27);
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Pepe', 'Federer', 'pfederer', 50);
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Pedro', 'Nadal', 'pnadal', 31);
INSERT INTO PERSON(NAME, SURNAME, LOGIN, AGE) VALUES ('Jose Pablo', 'Serna', 'jpserna', 29);

-- Insertar deportes
INSERT INTO SPORT(DESCRIPTION) VALUES ('Tennis');
INSERT INTO SPORT(DESCRIPTION) VALUES ('Football');
INSERT INTO SPORT(DESCRIPTION) VALUES ('Basketball');
INSERT INTO SPORT(DESCRIPTION) VALUES ('Atletism');

-- Insertar pistas
INSERT INTO COURT(DESCRIPTION, ID_SPORT) VALUES ('Tennis Court 1', 1);
INSERT INTO COURT(DESCRIPTION, ID_SPORT) VALUES ('Tennis Court 2', 1);
INSERT INTO COURT(DESCRIPTION, ID_SPORT) VALUES ('Football Court', 2);
INSERT INTO COURT(DESCRIPTION, ID_SPORT) VALUES ('Basketball Court', 3);
INSERT INTO COURT(DESCRIPTION, ID_SPORT) VALUES ('Atletism Court', 4);

-- Insertar turnos
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (1, '20:30:00','21:30:00');--1
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (1, '21:30:00','22:30:00');--2
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (2, '20:30:00','21:30:00');--3
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (2, '21:30:00','22:30:00');--4
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (3, '20:30:00','21:30:00');--5
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (3, '21:30:00','22:30:00');--6
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (4, '20:30:00','21:30:00');--7
INSERT INTO SCHEDULE(WEEK_DAY, START_HOUR, END_HOUR) VALUES (4, '21:30:00','22:30:00');--8

-- Insertar grupos
INSERT INTO `GROUP`(ID_SPORT) VALUES (1);
INSERT INTO `GROUP`(ID_SPORT) VALUES (1);
INSERT INTO GROUP_SCHEDULE(ID_GROUP, ID_SCHEDULE) VALUES (1, 1);
INSERT INTO GROUP_SCHEDULE(ID_GROUP, ID_SCHEDULE) VALUES (1, 5);
INSERT INTO GROUP_SCHEDULE(ID_GROUP, ID_SCHEDULE) VALUES (2, 2);
INSERT INTO GROUP_SCHEDULE(ID_GROUP, ID_SCHEDULE) VALUES (2, 6);